cd E:\work\link_extractor\ResearchGateSpider

scrapy crawl RGSpider1 -a start_url=http://uconn.edu/ -a domain=uconn.edu -a university="University of Connecticut"
scrapy crawl RGSpider1 -a start_url=http://www.usf.edu/ -a domain=usf.edu -a university="University of South Florida"
scrapy crawl RGSpider1 -a start_url=http://www.smu.edu/ -a domain=smu.edu -a university="Southern Methodist University"
scrapy crawl RGSpider1 -a start_url=https://umich.edu/ -a domain=umich.edu -a university="University of Michigan-Ann Arbor"
scrapy crawl RGSpider1 -a start_url=https://www.syracuse.edu/ -a domain=syracuse.edu -a university="Syracuse University"
scrapy crawl RGSpider1 -a start_url=http://www.utexas.edu/ -a domain=utexas.edu -a university="The University of Texas at Austin"
scrapy crawl RGSpider1 -a start_url=https://www.stevens.edu/ -a domain=stevens.edu -a university="Stevens Institute of Technology"
scrapy crawl RGSpider1 -a start_url=http://www.esf.edu/ -a domain=esf.edu -a university="State University of New York College of Environmental Science and Forestry"
scrapy crawl RGSpider1 -a start_url=http://www.nova.edu/ -a domain=nova.edu -a university="Nova Southeastern University"
scrapy crawl RGSpider1 -a start_url=https://utulsa.edu/ -a domain=utulsa.edu -a university="University of Tulsa"
scrapy crawl RGSpider1 -a start_url=http://www.buffalo.edu/ -a domain=buffalo.edu -a university="SUNY at Buffalo"
scrapy crawl RGSpider1 -a start_url=http://www.gsu.edu/ -a domain=gsu.edu -a university="Georgia State University"
scrapy crawl RGSpider1 -a start_url=http://www.american.edu/ -a domain=american.edu -a university="American University"
scrapy crawl RGSpider1 -a start_url=http://www.ucsb.edu/ -a domain=ucsb.edu -a university="University of California-Santa Barbara"
scrapy crawl RGSpider1 -a start_url=http://www.newschool.edu/ -a domain=newschool.edu -a university="The New School  New York"
scrapy crawl RGSpider1 -a start_url=https://www.barry.edu/ -a domain=barry.edu -a university="Barry University"
scrapy crawl RGSpider1 -a start_url=https://www2.howard.edu/ -a domain=howard.edu -a university="Howard University"
scrapy crawl RGSpider1 -a start_url=http://www.hartford.edu/ -a domain=hartford.edu -a university="University of Hartford"


scrapy crawl RGSpider1 -a start_url=http://www.clemson.edu/ -a domain=clemson.edu -a university="Clemson University  Clemson"
scrapy crawl RGSpider1 -a start_url=https://www2.gmu.edu/ -a domain=gmu.edu -a university="George Mason University  Fairfax"
scrapy crawl RGSpider1 -a start_url=https://www.fsu.edu/ -a domain=fsu.edu -a university="Florida State University  Tallahassee"
scrapy crawl RGSpider1 -a start_url=http://www.clemson.edu/ -a domain=utdallas.edu -a university="The University of Texas at Dallas  Richardson"
scrapy crawl RGSpider1 -a start_url=http://www.uta.edu/uta/ -a domain=uta.edu -a university="The University of Texas at Arlington  Arlington"
scrapy crawl RGSpider1 -a start_url=http://www.pitt.edu/ -a domain=pitt.edu -a university="University of Pittsburgh"
scrapy crawl RGSpider1 -a start_url=http://www.albany.edu/ -a domain=albany.edu -a university="SUNY at Albany  Albany"
scrapy crawl RGSpider1 -a start_url=http://www.clarku.edu/ -a domain=clarku.edu -a university="Clark University  Worcester"
scrapy crawl RGSpider1 -a start_url=http://newbrunswick.rutgers.edu/ -a domain=newbrunswick.rutgers.edu -a university="Rutgers University-New Brunswick  New Brunswick"
scrapy crawl RGSpider1 -a start_url=http://web.iit.edu/ -a domain=iit.edu -a university="Illinois Institute of Technology  Chicago"
scrapy crawl RGSpider1 -a start_url=http://www.fau.edu/ -a domain=fau.edu -a university="Florida Atlantic University"
scrapy crawl RGSpider1 -a start_url=https://twin-cities.umn.edu/ -a domain=twin-cities.umn.edu -a university="University of Minnesota-Twin Cities"
scrapy crawl RGSpider1 -a start_url=http://www.bridgeport.edu/ -a domain=bridgeport.edu -a university="University of Bridgeport  Bridgeport"
scrapy crawl RGSpider1 -a start_url=https://www.usm.edu/ -a domain=usm.edu -a university="University of Southern Mississippi  Hattiesburg"
scrapy crawl RGSpider1 -a start_url=http://www.uga.edu/ -a domain=uga.edu -a university="University of Georgia  Athens"
scrapy crawl RGSpider1 -a start_url=http://www.psu.edu/ -a domain=psu.edu -a university="Pennsylvania State University"
scrapy crawl RGSpider1 -a start_url=http://www.bu.edu/ -a domain=bu.edu -a university="Boston University  Boston"
scrapy crawl RGSpider1 -a start_url=https://www.osu.edu/ -a domain=osu.edu -a university="Ohio State University"
scrapy crawl RGSpider1 -a start_url=http://www.pacific.edu/ -a domain=pacific.edu -a university="University of the Pacific"
scrapy crawl RGSpider1 -a start_url=http://www.stjohns.edu/ -a domain=stjohns.edu -a university="St. John's University-New York"
scrapy crawl RGSpider1 -a start_url=http://www.udel.edu/ -a domain=udel.edu -a university="University of Delaware"
scrapy crawl RGSpider1 -a start_url=http://www.unh.edu/ -a domain=unh.edu -a university="University of New Hampshire"
scrapy crawl RGSpider1 -a start_url=https://laverne.edu/ -a domain=laverne.edu -a university="University of La Verne"
scrapy crawl RGSpider1 -a start_url=http://www.regent.edu/ -a domain=regent.edu -a university="Regent University"
scrapy crawl RGSpider1 -a start_url=https://www.ucf.edu/ -a domain=ucf.edu -a university="University of Central Florida"
scrapy crawl RGSpider1 -a start_url=https://uci.edu/ -a domain=uci.edu -a university="University of California-Irvine"
scrapy crawl RGSpider1 -a start_url=http://www.umkc.edu/ -a domain=umkc.edu -a university="University of Missouri-Kansas City"
scrapy crawl RGSpider1 -a start_url=https://www.mines.edu/ -a domain=mines.edu -a university="Colorado School of Mines"